version: '3.1'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    expose:
      - "15672"

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jake
      MYSQL_USER: jake
      MYSQL_PASSWORD: jake
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
