# Generated by Django 4.2.3 on 2023-07-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "url",
                    models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True, unique=True),
                ),
                (
                    "url_md5",
                    models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True, unique=True),
                ),
                ("title", models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True)),
                ("content", models.TextField(blank=True, db_collation="utf8mb4_0900_ai_ci", null=True)),
                ("section", models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True)),
                ("image_url", models.TextField(blank=True, db_collation="utf8mb4_0900_ai_ci", null=True)),
                ("portal", models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True)),
                ("media", models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True)),
                ("published", models.CharField(blank=True, db_collation="utf8mb4_0900_ai_ci", max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "news_article",
                "managed": True,
            },
        ),
    ]
